export const COMMON_EXERCISES = [
  'Bench Press',
  'Squat',
  'Deadlift',
  'Shoulder Press',
  'Pull Ups',
  'Dumbbell Bench Press',
  'Dumbbell Curl',
  'Push Ups',
  'Sled Leg Press',
  'Barbell Curl',
  'Incline Dumbbell Bench Press',
  'Bent Over Row',
  'Incline Bench Press',
  'Dips',
  'Dumbbell Shoulder Press',
  'Lat Pulldown',
  'Front Squat',
  'Hex Bar Deadlift',
  'Chin Ups',
  'Hip Thrust',
  'Dumbbell Lateral Raise',
  'Leg Extension',
  'Power Clean',
  'Horizontal Leg Press',
  'Dumbbell Row',
  'Military Press',
  'Sumo Deadlift',
  'Chest Press',
  'Hammer Curl',
  'Seated Cable Row',
  'Crunches',
  'Sit Ups',
  'Seated Dumbbell Shoulder Press',
  'Muscle Ups',
  'Hack Squat',
  'Bodyweight Squat',
  'Machine Shoulder Press',
  'Machine Chest Fly',
  'Dumbbell Bulgarian Split Squat',
  'Clean and Jerk',
  'Seated Leg Curl',
  'EZ Bar Curl',
  'Lying Tricep Extension',
  'One Arm Push Ups',
  'Close Grip Bench Press',
  'Snatch',
  'Preacher Curl',
  'Seated Shoulder Press',
  'Goblet Squat',
  'Barbell Shrug',
  'T Bar Row',
  'Clean',
  'Lying Leg Curl',
  'Neutral Grip Pull Ups',
  'Machine Calf Raise',
  'Push Press',
  'Dumbbell Fly',
  'Diamond Push Ups',
  'Hip Adduction',
  'Smith Machine Bench Press',
  'Dumbbell Shrug',
  'Decline Bench Press',
  'Dumbbell Lunge',
  'Pistol Squat',
  'Hanging Leg Raise',
  'Machine Row',
  'Tricep Rope Pushdown',
  'Chest Supported Dumbbell Row',
  'Dumbbell Romanian Deadlift',
  'Clean and Press',
  'Bulgarian Split Squat',
  'Smith Machine Squat',
  'Rack Pull',
  'Dumbbell Tricep Extension',
  'Box Squat',
  'Pendlay Row',
  'Incline Dumbbell Curl',
  'Cable Bicep Curl',
  'Seated Calf Raise',
  'Close Grip Lat Pulldown',
  'Upright Row',
  'Vertical Leg Press',
  'Machine Bicep Curl',
  'Zercher Squat',
  'Cable Lateral Raise',
  'Stiff Leg Deadlift',
  'Jumping Jack',
  'Arnold Press',
  'Hang Clean',
  'Dumbbell Reverse Fly',
  'Incline Dumbbell Fly',
  'Dumbbell Concentration Curl',
  'Decline Push Up',
  'Back Extension',
  'Cable Crunch',
  'Dumbbell Front Raise',
  'Seated Dip Machine',
  'One Arm Pull Ups',
  'Tricep Extension',
  'Good Morning',
  'Floor Press',
  'Dumbbell Pullover',
  'Hip Abduction',
  'Cable Fly',
  'Dumbbell Floor Press',
  'Lunge',
  'Barbell Lunge',
  'Single Leg Squat',
  'Handstand Push Ups',
  'Dumbbell Squat',
  'Burpees',
  'Thruster',
  'Face Pull',
  'Barbell Calf Raise',
  'Wrist Curl',
  'Close Grip Push Up',
  'Bodyweight Calf Raise',
  'Overhead Squat',
  'Russian Twist',
  'Lying Dumbbell Tricep Extension',
  'Paused Bench Press',
  'Lying Leg Raise',
  'Glute Bridge',
  'Power Snatch',
  'Cable Overhead Tricep Extension',
  'Behind The Neck Press',
  'Machine Reverse Fly',
  'Split Squat',
  'Cable Reverse Fly',
  'Dumbbell Deadlift',
  'Dumbbell Calf Raise',
  'Push Jerk',
  'Squat Jump',
  'Reverse Barbell Curl',
  'Sissy Squat',
  'Dumbbell Tricep Kickback',
  'Decline Dumbbell Bench Press',
  'Close Grip Dumbbell Bench Press',
  'Reverse Grip Lat Pulldown',
  'Sled Press Calf Raise',
  'Single Leg Press',
  'Barbell Reverse Lunge',
  'Incline Push Up',
  'Belt Squat',
  'One Arm Dumbbell Preacher Curl',
  'Barbell Glute Bridge',
  'Reverse Grip Bench Press',
  'Reverse Lunge',
  'Standing Leg Curl',
  'Cable Pull Through',
  'Landmine Squat',
  'Straight Arm Pulldown',
  'Safety Bar Squat',
  'Dumbbell Wrist Curl',
  'Dumbbell Upright Row',
  'Deficit Deadlift',
  'Strict Curl',
  'Snatch Deadlift',
  'Machine Back Extension',
  'Decline Crunch',
  'One Arm Cable Bicep Curl',
  'Sumo Squat',
  'Hang Power Clean',
  'Single Leg Romanian Deadlift',
  'Pause Deadlift',
  'Barbell Hack Squat',
  'Bench Pull',
  'Machine Tricep Extension',
  'Seated Dumbbell Tricep Extension',
  'Side Lunge',
  'Jefferson Deadlift',
  'Bicycle Crunch',
  'Yates Row',
  'Reverse Wrist Curl',
  'Pin Squat',
  'Side Crunch',
  'Pause Squat',
  'Inverted Row',
  'Machine Lateral Raise',
  'Hex Bar Shrug',
  'Single Leg Dumbbell Deadlift',
  'Smith Machine Shrug',
  'Dumbbell Side Bend',
  'Barbell Front Raise',
  'Half Squat',
  'Split Jerk',
  'Bench Pin Press',
  'JM Press',
  'Barbell Power Shrug',
  'Behind The Back Barbell Shrug',
  'Neck Curl',
  'Clean High Pull',
  'Hanging Knee Raise',
  'Glute Kickback',
  'Ring Dips',
  'Bent Over Dumbbell Row',
  'Behind The Back Deadlift',
  'Clean Pull',
  'Wide Grip Bench Press',
  'Hip Extension',
  'Jefferson Squat',
  'Squat Thrust',
  'Pike Push Up',
  'Walking Lunge',
  'Cheat Curl',
  'Archer Push Ups',
  'Muscle Snatch',
  'Glute Ham Raise',
  'Reverse Crunches',
  'Z Press',
  'Close Grip Incline Bench Press',
  'Reverse Hyperextension',
  'Shoulder Pin Press',
  'Side Leg Raise',
  'Snatch Pull',
  'Nordic Hamstring Curl',
  'Cable Upright Row',
  'Barbell Pullover',
  'Machine Shrug',
  'Toes To Bar',
  'Dumbbell Snatch',
  'Landmine Press',
  'Incline Hammer Curl',
  'Cable Kickback',
  'Seated Dumbbell Curl',
  'Neck Extension',
  'Cable Woodchopper',
  'Meadows Row',
  'Cable Leg Extension',
  'Cable Shrug',
  'Single Leg Seated Calf Raise',
  'One Arm Lat Pulldown',
  'One Arm Pulldown',
  'Hang Snatch',
  'Spoto Press',
  'Spider Curl',
  'Dumbbell Reverse Wrist Curl',
  'Standing Cable Crunch',
  'High Pulley Crunch',
  'Overhead Cable Curl',
  'Roman Chair Side Bend',
  'Zottman Curl',
  'Renegade Row',
  'Incline Cable Curl',
  'Lying Cable Curl',
  'Dumbbell Bench Pull',
  'One Arm Landmine Press',
  'Dumbbell Front Squat',
  'One Arm Seated Cable Row',
  'Cable Hammer Curl',
  'Tate Press',
  'Floor Hip Extension',
  'Dumbbell Split Squat',
  'Dumbbell Z Press',
  'Wall Ball',
  'Dumbbell Reverse Curl',
  'Floor Hip Abduction',
  'Clap Pull Up',
  'Bent Arm Barbell Pullover',
  'Ring Muscle Ups',
  'Dumbbell Thruster',
  'Dumbbell Face Pull',
  'Dumbbell High Pull',
  'Dumbbell External Rotation',
  'Dumbbell Hang Clean',
  'Dumbbell Push Press',
  'Dumbbell Walking Calf Raise',
  'Dumbbell Incline Y Raise',
  'Dumbbell Clean and Press',
  'Cable External Rotation',
  'Flutter Kicks',
  'Mountain Climbers',
  'Donkey Calf Raise',
  'Superman',
  'Scissor Kicks'
];
